// Generated by CoffeeScript 1.8.0
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(request, response) {
    response.writeHead(200, {
      "content-Type": "text/plain"
    });
    return response.end("Hello World");
  });

  server.listen(8080);

  console.log("Server running on 8080");

}).call(this);
